numbers = [5, 2, 1, 7, 4]
numbers.append(20)
print(numbers)
numbers.insert(0, 8)
print(numbers)
numbers.remove(5)
print(numbers)
# print(numbers.index(5))
print(numbers.count(7))
numbers.sort()
print(numbers)
